---
- name: deploy easybuild
  hosts: easybuild
  gather_facts: no
  become: yes
  roles: [easybuild]
  post_tasks:
    - name: add vagrant user to easybuild group
      user: name=vagrant groups=easybuild append=yes
